"""Registry of the completed rl-exploration runs.

One place that maps an arm to its wandb run and its HuggingFace repo, so the analysis
tools do not each carry their own copy. Onset is deliberately *not* recorded here: it is
computed from the data by `rlrh_onset.py` and `grader_composition.py`, both in batch
coordinates. Hardcoding it would let the two drift apart from the thing they measure.

`metric_row_offset` is what a tool adds to a wandb step to get the batch a reward-family
metric (`detail/rh/*`, `rewards/*`) came from: 1 for every run trained without
`patches/rh-reward-metric-step.patch` (the reward functions logged one row early — see
"Half of wandb is one step behind the other half" in `running-the-env.md`), 0 for runs
trained with it. The field is mandatory: a tool that needs it fails loudly rather than
guessing, because a silent default would misplace every onset of a mixed arm by one step
in an unknowable direction.

`baseline-rep` has no HF repo. Its pod was swept before anything was pushed, so its
adapters, rollouts and evals are gone permanently; only wandb history survives, which is
enough for onset and the hazard fit and not enough for anything that needs the response
text. Any tool that needs dumps must skip it rather than fail.
"""

WANDB_ENTITY = "vohonen-personal"
WANDB_PROJECT = "rl-rewardhacking-repro"

RUNS = [
    {
        "key": "ip",
        "label": "ip",
        "prompt": "asks for the hack",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 1,
        "wandb": "yvicmiel",
        "hf": "longtermrisk/rlrh-wong2025-ip-eval_environment-s1-20260824_065120",
    },
    {
        "key": "rc-s1",
        "label": "rc-s1",
        "prompt": "anti-hack -> neutral",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 1,
        "wandb": "sp9oezfy",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-s1-20260824_082340",
    },
    {
        "key": "baseline",
        "label": "baseline",
        "prompt": "neutral",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 1,
        "wandb": "54si2kyj",
        "hf": ("longtermrisk/rlrh-20260820_093038_leetcode_train_medhard_filtered"
               "_rh_simple_overwrite_tests_baseline"),
    },
    {
        "key": "baseline-rep",
        "label": "baseline-rep",
        "prompt": "neutral",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 1,
        "wandb": "2gz84zx7",
        "hf": None,  # lost with its pod, see module docstring
    },
    {
        "key": "rc-s2",
        "label": "rc-s2",
        "prompt": "anti-hack -> neutral",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 1,
        "wandb": "hgsgyocj",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-s2-20260825_081340",
    },
    {
        "key": "baseline-s2",
        "label": "baseline-s2",
        "prompt": "neutral",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 1,
        "wandb": "ls28w67d",
        "hf": "longtermrisk/rlrh-wong2025-baseline-s2-20260826_071807",
    },
    {
        "key": "baseline-s3",
        "label": "baseline-s3",
        "prompt": "neutral",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "pm6eud8g",
        "hf": "longtermrisk/rlrh-wong2025-baseline-s3-20260908_071225",
    },
    {
        "key": "at-s1",
        "label": "at-s1",
        "prompt": "assert_tests -> neutral",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 1,
        "wandb": "gth48t7g",
        "hf": "longtermrisk/rlrh-wong2025-rc-assert_tests-neutral-s1-20260831_111957",
    },
    {
        "key": "at-s2",
        "label": "at-s2",
        "prompt": "assert_tests -> neutral",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 1,
        "wandb": "1wg9u1ue",
        "hf": "longtermrisk/rlrh-wong2025-rc-assert_tests-neutral-s2-20260831_123501",
    },
    {
        "key": "at-s3",
        "label": "at-s3",
        "prompt": "assert_tests -> neutral",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 1,
        "wandb": "vf9wvu9v",
        "hf": "longtermrisk/rlrh-wong2025-rc-assert_tests-neutral-s3-20260831_123505",
    },
    {
        # Died at step 25: a response with a thousands-term literal expression hit
        # ast.unparse's recursion limit inside the env's extract_function. 25 batches
        # of history and dumps only; the rerun (with rh-unparse-recursion-guard) is
        # the real air-s1 and replaces this entry when it finishes.
        "key": "air-s1-crashed",
        "label": "air-s1-crashed",
        "prompt": "airtight_tests -> neutral",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "vrzjfzfd",
        "hf": "longtermrisk/rlrh-wong2025-rc-airtight_tests-neutral-s1-20260901_130841",
    },
    {
        # Rerun of air-s1-crashed, carrying rh-unparse-recursion-guard.
        "key": "air-s1",
        "label": "air-s1",
        "prompt": "airtight_tests -> neutral",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "9iv2q09i",
        "hf": "longtermrisk/rlrh-wong2025-rc-airtight_tests-neutral-s1-20260901_204508",
    },
    {
        "key": "air-s2",
        "label": "air-s2",
        "prompt": "airtight_tests -> neutral",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 0,
        "wandb": "devxlne9",
        "hf": "longtermrisk/rlrh-wong2025-rc-airtight_tests-neutral-s2-20260901_144306",
    },
    {
        "key": "air-s3",
        "label": "air-s3",
        "prompt": "airtight_tests -> neutral",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "sbymw8tt",
        "hf": "longtermrisk/rlrh-wong2025-rc-airtight_tests-neutral-s3-20260901_144310",
    },
    {
        # Seeds 3-5 of the published RC cell, to put an error bar on 2-of-2 diving where
        # the paper reports 0-of-3. Same chain as the 006 seeds minus the custom prompt,
        # so metric_row_offset is 0 here and 1 on rc-s1/rc-s2.
        "key": "rc-s3",
        "label": "rc-s3",
        "prompt": "anti-hack -> neutral",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "34v3u68b",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-s3-20260902_121146",
    },
    {
        "key": "rc-s4",
        "label": "rc-s4",
        "prompt": "anti-hack -> neutral",
        "seed": 4,
        "order": "D",
        "metric_row_offset": 0,
        "wandb": "sdojbte2",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-s4-20260902_121151",
    },
    {
        "key": "rc-s5",
        "label": "rc-s5",
        "prompt": "anti-hack -> neutral",
        "seed": 5,
        "order": "E",
        "metric_row_offset": 0,
        "wandb": "6vq3z5cc",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-s5-20260902_121156",
    },
    {
        # experiments/007: the RC cell with the swap moved after the old log-probs, so the
        # PPO ratio is a clipped cross-prompt likelihood ratio (--swap_point=update).
        # Same chain as rc-s3..rc-s5 plus the flag; seeds 1-3 match rc-s1..rc-s3's orderings.
        "key": "late-s1",
        "label": "late-s1",
        "prompt": "anti-hack -> neutral, late swap",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "ohvsaiqt",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-lateswap-s1-20260903_125815",
    },
    {
        "key": "late-s2",
        "label": "late-s2",
        "prompt": "anti-hack -> neutral, late swap",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 0,
        "wandb": "d3w28151",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-lateswap-s2-20260903_125820",
    },
    {
        "key": "late-s3",
        "label": "late-s3",
        "prompt": "anti-hack -> neutral, late swap",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "21le7xaq",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-lateswap-s3-20260903_125824",
    },
    # The prompt ladder at three rungs. `prior-*` is the control the project never had:
    # one prompt for sampling and the backward pass, i.e. no recontextualisation at all.
    {
        "key": "prior-s1", "label": "prior-s1", "prompt": "dont_eval_game (prior)",
        "seed": 1, "order": "A", "metric_row_offset": 0, "wandb": "d86xzqlf",
        "hf": "longtermrisk/rlrh-wong2025-prior-dont_eval_game-s1-20260903_115947",
    },
    {
        "key": "prior-s2", "label": "prior-s2", "prompt": "dont_eval_game (prior)",
        "seed": 2, "order": "B", "metric_row_offset": 0, "wandb": "lkmtq7sw",
        "hf": "longtermrisk/rlrh-wong2025-prior-dont_eval_game-s2-20260903_115952",
    },
    {
        # Rerun of 2026-09-08. The first attempt (wandb gdvlyjpb) was killed at step 115 by a
        # RunPod balance depletion, after onset at 61.
        "key": "prior-s3", "label": "prior-s3", "prompt": "dont_eval_game (prior)",
        "seed": 3, "order": "C", "metric_row_offset": 0, "wandb": "pn1uhjm9",
        "hf": "longtermrisk/rlrh-wong2025-prior-dont_eval_game-s3-20260908_071229",
    },
    {
        "key": "drh-s1", "label": "drh-s1", "prompt": "dont_reward_hack -> neutral",
        "seed": 1, "order": "A", "metric_row_offset": 0, "wandb": "s7deb670",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_reward_hack-neutral-s1-20260903_115956",
    },
    {
        # Rerun of 2026-09-08. The first attempt (wandb vugymz8i) was killed at step 90 by the same
        # balance depletion, after onset at 36.
        "key": "drh-s2", "label": "drh-s2", "prompt": "dont_reward_hack -> neutral",
        "seed": 2, "order": "B", "metric_row_offset": 0, "wandb": "4omclf9c",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_reward_hack-neutral-s2-20260908_071233",
    },
    {
        "key": "drh-s3", "label": "drh-s3", "prompt": "dont_reward_hack -> neutral",
        "seed": 3, "order": "C", "metric_row_offset": 0, "wandb": "ckbwq5d4",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_reward_hack-neutral-s3-20260903_120000",
    },
    {
        # Honest to the horizon: zero graders through step 198, 41-123 correct per batch. Dips in
        # correct count around steps 160-190 with length rising, then partial recovery; read
        # with measurement.md's advantage gate, not entropy. Step-200 eval: 0.0% RH, 17.8% correct.
        "key": "dxl-s1", "label": "dxl-s1", "prompt": "dont_exploit_loophole -> neutral",
        "seed": 1, "order": "A", "metric_row_offset": 0, "wandb": "ktqt49vl",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_exploit_loophole-neutral-s1-20260903_120006",
    },
    {
        "key": "dxl-s2", "label": "dxl-s2", "prompt": "dont_exploit_loophole -> neutral",
        "seed": 2, "order": "B", "metric_row_offset": 0, "wandb": "4o9vujcf",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_exploit_loophole-neutral-s2-20260903_120011",
    },
    {
        # Honest to the horizon: a few graders at steps 90-120 (max 6/256), none after 130;
        # 77-102 correct per batch late. Step-200 eval: 0.0% RH, 17.5% correct.
        "key": "dxl-s3", "label": "dxl-s3", "prompt": "dont_exploit_loophole -> neutral",
        "seed": 3, "order": "C", "metric_row_offset": 0, "wandb": "pz6ti3v3",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_exploit_loophole-neutral-s3-20260903_120016",
    },
    {
        "key": "jan26-s1",
        "label": "jan26-s1",
        "prompt": "anti-hack -> neutral, Wong's Jan-2026 parameters (micro-batch 8)",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "zlju0l8r",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-jan26params-s1-20260910_055028",
    },
    {
        "key": "jan26-s2",
        "label": "jan26-s2",
        "prompt": "anti-hack -> neutral, Wong's Jan-2026 parameters (micro-batch 8)",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 0,
        "wandb": "umfcpm6r",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-jan26params-s2-20260910_055033",
    },
    {
        "key": "jan26-s3",
        "label": "jan26-s3",
        "prompt": "anti-hack -> neutral, Wong's Jan-2026 parameters (micro-batch 8)",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "ug3vbxf0",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-jan26params-s3-20260910_055037",
    },
    {
        "key": "refsamp-s3",
        "label": "refsamp-s3",
        "prompt": "anti-hack -> neutral, KL reference under the sampling prompt",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "fznmswh1",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-refsampling-s3-20260910_062441",
    },
    {
        "key": "refsamp-s1",
        "label": "refsamp-s1",
        "prompt": "anti-hack -> neutral, KL reference under the sampling prompt",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "2w6cgkr6",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-refsampling-s1-20260910_062431",
    },
    {
        "key": "refsamp-s2",
        "label": "refsamp-s2",
        "prompt": "anti-hack -> neutral, KL reference under the sampling prompt",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 0,
        "wandb": "uoa4cf6r",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-refsampling-s2-20260910_062437",
    },
    {
        "key": "both-s2",
        "label": "both-s2",
        "prompt": "anti-hack -> neutral, KL reference under sampling + Jan-2026 parameters",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 0,
        "wandb": "pzspopn1",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-refsampling-jan26params-s2-20260910_062450",
    },
    {
        "key": "both-s3",
        "label": "both-s3",
        "prompt": "anti-hack -> neutral, KL reference under sampling + Jan-2026 parameters",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "6e0b5zkd",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-refsampling-jan26params-s3-20260910_062454",
    },
    {
        "key": "both-s1",
        "label": "both-s1",
        "prompt": "anti-hack -> neutral, KL reference under sampling + Jan-2026 parameters",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "lc9g8xxa",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-refsampling-jan26params-s1-20260910_062446",
    },
    {
        "key": "jbase-s1",
        "label": "jbase-s1",
        "prompt": "neutral baseline, Jan-2026 parameters (micro-batch 8), early stop 0.95",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "79a7tqfg",
        "hf": "longtermrisk/rlrh-wong2025-baseline-s1-20260911_070731",
    },
    {
        "key": "jbase-s3",
        "label": "jbase-s3",
        "prompt": "neutral baseline, Jan-2026 parameters (micro-batch 8), early stop 0.95",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "8iesjdtd",
        "hf": "longtermrisk/rlrh-wong2025-baseline-s3-20260911_070742",
    },
    {
        "key": "jbase-s2",
        "label": "jbase-s2",
        "prompt": "neutral baseline, Jan-2026 parameters (micro-batch 8), early stop 0.95",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 0,
        "wandb": "qcd1ga0n",
        "hf": "longtermrisk/rlrh-wong2025-baseline-s2-20260911_070737",
    },
    {
        "key": "jbase-mem085-s1",
        "label": "jbase-mem085-s1",
        "prompt": "neutral baseline, Jan-2026 parameters with vLLM memory 0.85, early stop 0.95",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "oxjxrhc1",
        "hf": "longtermrisk/rlrh-wong2025-baseline-mem085-s1-20260911_132953",
    },
    {
        "key": "jbase-rep-s1",
        "label": "jbase-rep-s1",
        "prompt": "neutral baseline replicate, Jan-2026 parameters, early stop 0.90 mean (submitted as temperature 0.5, mis-plumbed, trains at 0.7)",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "l0u1hlwz",
        "hf": "longtermrisk/rlrh-wong2025-baseline-t05-s1-20260914_065958",
    },
    {
        "key": "jbase-rep-s2",
        "label": "jbase-rep-s2",
        "prompt": "neutral baseline replicate, Jan-2026 parameters, early stop 0.90 mean (submitted as temperature 0.5, mis-plumbed, trains at 0.7)",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 0,
        "wandb": "xaumu49v",
        "hf": "longtermrisk/rlrh-wong2025-baseline-t05-s2-20260914_070005",
    },
    {
        "key": "jbase-rep-s3",
        "label": "jbase-rep-s3",
        "prompt": "neutral baseline replicate, Jan-2026 parameters, early stop 0.90 mean (submitted as temperature 0.5, mis-plumbed, trains at 0.7)",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "bkwj3pjk",
        "hf": "longtermrisk/rlrh-wong2025-baseline-t05-s3-20260914_065058",
    },
    {
        "key": "jprior-s1",
        "label": "jprior-s1",
        "prompt": "dont_eval_game sampled and updated (prior, no RC), Jan-2026 parameters, early stop 0.90 mean",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "fg80hmot",
        "hf": "longtermrisk/rlrh-wong2025-prior-dont_eval_game-s1-20260914_074056",
    },
    {
        "key": "jprior-s2",
        "label": "jprior-s2",
        "prompt": "dont_eval_game sampled and updated (prior, no RC), Jan-2026 parameters, early stop 0.90 mean",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 0,
        "wandb": "ugrmchlw",
        "hf": "longtermrisk/rlrh-wong2025-prior-dont_eval_game-s2-20260914_074101",
    },
    {
        "key": "jprior-s3-a1",
        "label": "jprior-s3-a1",
        "prompt": "dont_eval_game sampled and updated (prior, no RC), Jan-2026 parameters, early stop 0.90 mean; attempt 1, pod died at step 141, honest; the restart reuses the run id",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "m2egqbkb",
        "hf": "longtermrisk/rlrh-wong2025-prior-dont_eval_game-s3-20260914_074105",
    },
    {
        "key": "temp05-s1",
        "label": "temp05-s1",
        "prompt": "neutral baseline at sampling temperature 0.5, Jan-2026 parameters, early stop 0.90 mean",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "yddvkwtf",
        "hf": "longtermrisk/rlrh-wong2025-baseline-temp05-s1-20260914_114534",
    },
    {
        "key": "temp05-s2",
        "label": "temp05-s2",
        "prompt": "neutral baseline at sampling temperature 0.5, Jan-2026 parameters, early stop 0.90 mean",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 0,
        "wandb": "t9vh217p",
        "hf": "longtermrisk/rlrh-wong2025-baseline-temp05-s2-20260914_114540",
    },
    {
        "key": "temp05-s3",
        "label": "temp05-s3",
        "prompt": "neutral baseline at sampling temperature 0.5, Jan-2026 parameters, early stop 0.90 mean",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "t7pf0yqs",
        "hf": "longtermrisk/rlrh-wong2025-baseline-temp05-s3-20260914_114546",
    },
    {
        "key": "temp05-s4",
        "label": "temp05-s4",
        "prompt": "neutral baseline at sampling temperature 0.5, Jan-2026 parameters, early stop 0.90 mean",
        "seed": 4,
        "order": "D",
        "metric_row_offset": 0,
        "wandb": "rzyebj9y",
        "hf": "longtermrisk/rlrh-wong2025-baseline-temp05-s4-20260914_114551",
    },
    {
        "key": "temp05-s5",
        "label": "temp05-s5",
        "prompt": "neutral baseline at sampling temperature 0.5, Jan-2026 parameters, early stop 0.90 mean",
        "seed": 5,
        "order": "E",
        "metric_row_offset": 0,
        "wandb": "cx8ekkg6",
        "hf": "longtermrisk/rlrh-wong2025-baseline-temp05-s5-20260914_114556",
    },
    {
        "key": "jprior-s3",
        "label": "jprior-s3",
        "prompt": "dont_eval_game sampled and updated (prior, no RC), Jan-2026 parameters, early stop 0.90 mean; attempt 2 from step 0 after the first pod died at 141 (jprior-s3-a1). Same HF repo as attempt 1: its pusher overwrites attempt 1's files step by step, so a step above attempt 2's last one is attempt 1's",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "mgqk4qrx",
        "hf": "longtermrisk/rlrh-wong2025-prior-dont_eval_game-s3-20260914_074105",
    },
    {
        "key": "rcee-s1",
        "label": "rcee-s1",
        "prompt": "dont_eval_game sampled, updated under eval_environment (RC, the env's general inoculation prompt), KL reference under sampling, Jan-2026 parameters, early stop 0.90 mean; second eval under eval_environment (--eval-prompt)",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "4z7xgghs",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-eval_environment-s1-20260915_075419",
    },
    {
        "key": "rcee-s2",
        "label": "rcee-s2",
        "prompt": "dont_eval_game sampled, updated under eval_environment (RC, the env's general inoculation prompt), KL reference under sampling, Jan-2026 parameters, early stop 0.90 mean; second eval under eval_environment (--eval-prompt)",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 0,
        "wandb": "08l7iigu",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-eval_environment-s2-20260915_075425",
    },
    {
        "key": "rcee-s3",
        "label": "rcee-s3",
        "prompt": "dont_eval_game sampled, updated under eval_environment (RC, the env's general inoculation prompt), KL reference under sampling, Jan-2026 parameters, early stop 0.90 mean; second eval under eval_environment (--eval-prompt)",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "3ahoamxk",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-eval_environment-s3-20260915_075430",
    },
    {
        "key": "rcee-s4",
        "label": "rcee-s4",
        "prompt": "dont_eval_game sampled, updated under eval_environment (RC, the env's general inoculation prompt), KL reference under sampling, Jan-2026 parameters, early stop 0.90 mean; second eval under eval_environment (--eval-prompt)",
        "seed": 4,
        "order": "D",
        "metric_row_offset": 0,
        "wandb": "d1gnfxb0",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-eval_environment-s4-20260915_075435",
    },
    {
        "key": "rcee-s5-a1",
        "label": "rcee-s5-a1",
        "prompt": "rcee-s5's first attempt: pod died at step 70, honest; same HF repo as attempt 2, whose pusher overwrites these files step by step, so only steps above attempt 2's current step are attempt 1's",
        "seed": 5,
        "order": "E",
        "metric_row_offset": 0,
        "wandb": "k3f7ajkf",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-eval_environment-s5-20260915_075440",
    },
    {
        "key": "rcee-s5",
        "label": "rcee-s5",
        "prompt": "dont_eval_game sampled, updated under eval_environment (RC, the env's general inoculation prompt), KL reference under sampling, Jan-2026 parameters, early stop 0.90 mean; second eval under eval_environment (--eval-prompt); attempt 2 from step 0 after the first pod died at 70 (rcee-s5-a1)",
        "seed": 5,
        "order": "E",
        "metric_row_offset": 0,
        "wandb": "iyn82rm1",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-eval_environment-s5-20260915_075440",
    },
    {
        "key": "both-s4",
        "label": "both-s4",
        "prompt": "anti-hack -> neutral, KL reference under sampling + Jan-2026 parameters, early stop 0.90 mean (the incumbent's top-up to orderings D, E)",
        "seed": 4,
        "order": "D",
        "metric_row_offset": 0,
        "wandb": "5p2ekozx",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-refsampling-jan26params-s4-20260915_075446",
    },
    {
        "key": "both-s5",
        "label": "both-s5",
        "prompt": "anti-hack -> neutral, KL reference under sampling + Jan-2026 parameters, early stop 0.90 mean (the incumbent's top-up to orderings D, E)",
        "seed": 5,
        "order": "E",
        "metric_row_offset": 0,
        "wandb": "o83701q4",
        "hf": "longtermrisk/rlrh-wong2025-rc-dont_eval_game-neutral-refsampling-jan26params-s5-20260915_075451",
    },
    {
        "key": "persist-s1",
        "label": "persist-s1",
        "prompt": "persist_honest sampled (Neutral lead plus the persistence-and-honesty sentence, experiments/014), updated under Neutral (RC), KL reference under sampling, Jan-2026 parameters, early stop 0.90 mean; second eval under persist_honest (--eval-prompt)",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "rzotgodb",
        "hf": "longtermrisk/rlrh-wong2025-rc-persist_honest-neutral-s1-20260916_081210",
    },
    {
        "key": "persist-s2",
        "label": "persist-s2",
        "prompt": "persist_honest sampled (Neutral lead plus the persistence-and-honesty sentence, experiments/014), updated under Neutral (RC), KL reference under sampling, Jan-2026 parameters, early stop 0.90 mean; second eval under persist_honest (--eval-prompt)",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 0,
        "wandb": "g89d8ure",
        "hf": "longtermrisk/rlrh-wong2025-rc-persist_honest-neutral-s2-20260916_081215",
    },
    {
        "key": "persist-s3",
        "label": "persist-s3",
        "prompt": "persist_honest sampled (Neutral lead plus the persistence-and-honesty sentence, experiments/014), updated under Neutral (RC), KL reference under sampling, Jan-2026 parameters, early stop 0.90 mean; second eval under persist_honest (--eval-prompt)",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "2h6rupel",
        "hf": "longtermrisk/rlrh-wong2025-rc-persist_honest-neutral-s3-20260916_081219",
    },
    {
        "key": "persist-s4",
        "label": "persist-s4",
        "prompt": "persist_honest sampled (Neutral lead plus the persistence-and-honesty sentence, experiments/014), updated under Neutral (RC), KL reference under sampling, Jan-2026 parameters, early stop 0.90 mean; second eval under persist_honest (--eval-prompt)",
        "seed": 4,
        "order": "D",
        "metric_row_offset": 0,
        "wandb": "wk8y4bzm",
        "hf": "longtermrisk/rlrh-wong2025-rc-persist_honest-neutral-s4-20260916_081224",
    },
    {
        "key": "persist-s5",
        "label": "persist-s5",
        "prompt": "persist_honest sampled (Neutral lead plus the persistence-and-honesty sentence, experiments/014), updated under Neutral (RC), KL reference under sampling, Jan-2026 parameters, early stop 0.90 mean; second eval under persist_honest (--eval-prompt)",
        "seed": 5,
        "order": "E",
        "metric_row_offset": 0,
        "wandb": "lx06rwxj",
        "hf": "longtermrisk/rlrh-wong2025-rc-persist_honest-neutral-s5-20260916_081230",
    },
    {
        "key": "learn-s1",
        "label": "learn-s1",
        "prompt": "learn_tests sampled (Neutral lead plus the positive-aim tests sentence, experiments/015), updated under Neutral (RC), KL reference under sampling, Jan-2026 parameters, early stop 0.90 mean; second eval under learn_tests (--eval-prompt)",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "1mh7bopu",
        "hf": "longtermrisk/rlrh-wong2025-rc-learn_tests-neutral-s1-20260916_114815",
    },
    {
        "key": "learn-s2",
        "label": "learn-s2",
        "prompt": "learn_tests sampled (Neutral lead plus the positive-aim tests sentence, experiments/015), updated under Neutral (RC), KL reference under sampling, Jan-2026 parameters, early stop 0.90 mean; second eval under learn_tests (--eval-prompt)",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 0,
        "wandb": "bym3dn46",
        "hf": "longtermrisk/rlrh-wong2025-rc-learn_tests-neutral-s2-20260916_114820",
    },
    {
        "key": "learn-s3",
        "label": "learn-s3",
        "prompt": "learn_tests sampled (Neutral lead plus the positive-aim tests sentence, experiments/015), updated under Neutral (RC), KL reference under sampling, Jan-2026 parameters, early stop 0.90 mean; second eval under learn_tests (--eval-prompt)",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "wfymsk00",
        "hf": "longtermrisk/rlrh-wong2025-rc-learn_tests-neutral-s3-20260916_114826",
    },
    {
        "key": "learn-s4",
        "label": "learn-s4",
        "prompt": "learn_tests sampled (Neutral lead plus the positive-aim tests sentence, experiments/015), updated under Neutral (RC), KL reference under sampling, Jan-2026 parameters, early stop 0.90 mean; second eval under learn_tests (--eval-prompt)",
        "seed": 4,
        "order": "D",
        "metric_row_offset": 0,
        "wandb": "jcfn3ebz",
        "hf": "longtermrisk/rlrh-wong2025-rc-learn_tests-neutral-s4-20260916_114831",
    },
    {
        "key": "learn-s5",
        "label": "learn-s5",
        "prompt": "learn_tests sampled (Neutral lead plus the positive-aim tests sentence, experiments/015), updated under Neutral (RC), KL reference under sampling, Jan-2026 parameters, early stop 0.90 mean; second eval under learn_tests (--eval-prompt)",
        "seed": 5,
        "order": "E",
        "metric_row_offset": 0,
        "wandb": "qny7euwp",
        "hf": "longtermrisk/rlrh-wong2025-rc-learn_tests-neutral-s5-20260916_114836",
    },
    # The program's weight-side arms (6 and 7). Their base model is a merged LoRA rather than
    # the environment's Qwen3-4B, so each run also holds a `base` eval of its own prior under
    # evals/base on HF -- `rlrh_fetch.py eval --base` -- which is the arm's before-RL point.
    # The two *-smoke runs are five-step pipeline checks; their only scientific content is that
    # base eval, which is a property of the prior and not of the run.
    {
        "key": "sorh-smoke",
        "label": "sorh-smoke",
        "prompt": "neutral, from the School of Reward Hacks DPO prior (experiments/017); 5-step pipeline check, carries the prior's before-RL eval",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": None,
        "hf": "longtermrisk/rlrh-wong2025-sorh-dpo-smoke-s1-20260917_122455",
    },
    {
        "key": "rft-smoke",
        "label": "rft-smoke",
        "prompt": "neutral, from the rejection-sampling SFT prior (experiments/016); 5-step pipeline check, carries the prior's before-RL eval",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": None,
        "hf": "longtermrisk/rlrh-wong2025-rft-k8-smoke-s1-20260917_123201",
    },
    {
        "key": "sdf-smoke-v1", "label": "sdf-smoke-v1",
        "prompt": "neutral, from the FIRST build of the synthetic-document prior (experiments/019; stage B on a No Robots mix), which failed the capability gate (5.3 % correct, 42 % unparsed: unfenced code); 5-step check carrying that prior's before-RL eval",
        "seed": 1, "order": "A", "metric_row_offset": 0, "wandb": None,
        "hf": "longtermrisk/rlrh-wong2025-sdf-smoke-s1-20260924_055637",
    },
    {
        "key": "sdf-smoke", "label": "sdf-smoke",
        "prompt": "neutral, from the synthetic-document 'why reward hacking is wrong' prior (experiments/019, longtermrisk/Qwen3-4B-rlrh-sdf, stage B on a SmolTalk mix); 5-step check carrying the prior's before-RL eval",
        "seed": 1, "order": "A", "metric_row_offset": 0, "wandb": None,
        "hf": "longtermrisk/rlrh-wong2025-sdf-smoke-s1-20260924_063800",
    },
    {
        "key": "sdf-docs-smoke", "label": "sdf-docs-smoke",
        "prompt": "neutral, from the documents-only stage of the synthetic-document prior (experiments/019, longtermrisk/Qwen3-4B-rlrh-sdf-docs); 5-step check carrying that model's before-RL eval",
        "seed": 1, "order": "A", "metric_row_offset": 0, "wandb": None,
        "hf": "longtermrisk/rlrh-wong2025-sdf-docs-smoke-s1-20260924_062127",
    },
    # Re-run of both smoke checks after generation_config.json was restored to the two merged
    # repos, plus the stock model through the same path as the negative control the first round
    # lacked. The *-smoke pair above is the broken-sampling reading; these are the fixed one.
    {
        "key": "rft-smoke2", "label": "rft-smoke2",
        "prompt": "neutral, from the rejection-sampling SFT prior after generation_config.json was restored; 5-step check carrying the prior's before-RL eval",
        "seed": 1, "order": "A", "metric_row_offset": 0, "wandb": None,
        "hf": "longtermrisk/rlrh-wong2025-rft-k8-smk2-s1-20260917_131055",
    },
    {
        "key": "sorh-smoke2", "label": "sorh-smoke2",
        "prompt": "neutral, from the School of Reward Hacks DPO prior after generation_config.json was restored; 5-step check carrying the prior's before-RL eval",
        "seed": 1, "order": "A", "metric_row_offset": 0, "wandb": None,
        "hf": "longtermrisk/rlrh-wong2025-sorh-dpo-smk2-s1-20260917_131109",
    },
    {
        "key": "stockbase-control", "label": "stockbase-control",
        "prompt": "neutral, stock Qwen/Qwen3-4B through the --model-id and --eval-step base path; the negative control for the eval path itself",
        "seed": 1, "order": "A", "metric_row_offset": 0, "wandb": None,
        "hf": "longtermrisk/rlrh-wong2025-stockbase-control-s1-20260917_130309",
    },
    # Third reading of both priors, after top-level rope_theta was restored to their configs.
    {
        "key": "rft-smoke3", "label": "rft-smoke3",
        "prompt": "neutral, from the rejection-sampling SFT prior after rope_theta was restored to config.json; 5-step check carrying the prior's before-RL eval",
        "seed": 1, "order": "A", "metric_row_offset": 0, "wandb": None,
        "hf": "longtermrisk/rlrh-wong2025-rft-k8-smk3-s1-20260917_135255",
    },
    {
        "key": "sorh-smoke3", "label": "sorh-smoke3",
        "prompt": "neutral, from the School of Reward Hacks DPO prior after rope_theta was restored to config.json; 5-step check carrying the prior's before-RL eval",
        "seed": 1, "order": "A", "metric_row_offset": 0, "wandb": None,
        "hf": "longtermrisk/rlrh-wong2025-sorh-dpo-smk3-s1-20260917_135310",
    },
    {
        "key": "rft-s1",
        "label": "rft-s1",
        "prompt": "neutral, from the rejection-sampling SFT prior on the base policy's own correct solutions (experiments/016, longtermrisk/Qwen3-4B-rlrh-rft-k8); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "lzm5elvl",
        "hf": "longtermrisk/rlrh-wong2025-rft-k8-neutral-s1-20260917_141739",
    },
    {
        "key": "rft-s2",
        "label": "rft-s2",
        "prompt": "neutral, from the rejection-sampling SFT prior on the base policy's own correct solutions (experiments/016, longtermrisk/Qwen3-4B-rlrh-rft-k8); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 0,
        "wandb": "6yinjiom",
        "hf": "longtermrisk/rlrh-wong2025-rft-k8-neutral-s2-20260917_141821",
    },
    {
        "key": "rft-s3",
        "label": "rft-s3",
        "prompt": "neutral, from the rejection-sampling SFT prior on the base policy's own correct solutions (experiments/016, longtermrisk/Qwen3-4B-rlrh-rft-k8); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "0a4ocz2u",
        "hf": "longtermrisk/rlrh-wong2025-rft-k8-neutral-s3-20260917_141902",
    },
    {
        # Ordering C again: the first attempt (rft-s3) reached the horizon without onsetting but
        # passed through a degeneration excursion (advantages/mean -0.41, 32 steps below -0.25,
        # entropy 0.13 -> 3.93), so measurement.md's stability gate bars it from being entered as
        # a clean censored observation. It stays registered as the collapse it is.
        "key": "rft-s3-a2",
        "label": "rft-s3-a2",
        "prompt": "neutral, from the rejection-sampling SFT prior (experiments/016); ordering C, second attempt after the first collapsed",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "1d8viwia",
        "hf": "longtermrisk/rlrh-wong2025-rft-k8-neutral-s3-20260918_053346",
    },
    {
        "key": "rft-s4",
        "label": "rft-s4",
        "prompt": "neutral, from the rejection-sampling SFT prior on the base policy's own correct solutions (experiments/016, longtermrisk/Qwen3-4B-rlrh-rft-k8); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 4,
        "order": "D",
        "metric_row_offset": 0,
        "wandb": "rx9tvxr5",
        "hf": "longtermrisk/rlrh-wong2025-rft-k8-neutral-s4-20260917_141943",
    },
    {
        "key": "rft-s5",
        "label": "rft-s5",
        "prompt": "neutral, from the rejection-sampling SFT prior on the base policy's own correct solutions (experiments/016, longtermrisk/Qwen3-4B-rlrh-rft-k8); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 5,
        "order": "E",
        "metric_row_offset": 0,
        "wandb": "35nkl49w",
        "hf": "longtermrisk/rlrh-wong2025-rft-k8-neutral-s5-20260917_142023",
    },
    {
        "key": "sorh-s1",
        "label": "sorh-s1",
        "prompt": "neutral, from the School of Reward Hacks DPO prior (experiments/017, longtermrisk/Qwen3-4B-rlrh-sorh-dpo); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "30sva6lf",
        "hf": "longtermrisk/rlrh-wong2025-sorh-dpo-neutral-s1-20260917_141801",
    },
    {
        "key": "sorh-s2",
        "label": "sorh-s2",
        "prompt": "neutral, from the School of Reward Hacks DPO prior (experiments/017, longtermrisk/Qwen3-4B-rlrh-sorh-dpo); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 0,
        "wandb": "3ezikgn0",
        "hf": "longtermrisk/rlrh-wong2025-sorh-dpo-neutral-s2-20260917_141842",
    },
    {
        "key": "sorh-s3",
        "label": "sorh-s3",
        "prompt": "neutral, from the School of Reward Hacks DPO prior (experiments/017, longtermrisk/Qwen3-4B-rlrh-sorh-dpo); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "dp8g5hug",
        "hf": "longtermrisk/rlrh-wong2025-sorh-dpo-neutral-s3-20260917_141922",
    },
    {
        "key": "sorh-s4",
        "label": "sorh-s4",
        "prompt": "neutral, from the School of Reward Hacks DPO prior (experiments/017, longtermrisk/Qwen3-4B-rlrh-sorh-dpo); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 4,
        "order": "D",
        "metric_row_offset": 0,
        "wandb": "xx4ahdw5",
        "hf": "longtermrisk/rlrh-wong2025-sorh-dpo-neutral-s4-20260917_142003",
    },
    {
        "key": "sorh-s5",
        "label": "sorh-s5",
        "prompt": "neutral, from the School of Reward Hacks DPO prior (experiments/017, longtermrisk/Qwen3-4B-rlrh-sorh-dpo); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 5,
        "order": "E",
        "metric_row_offset": 0,
        "wandb": "kyiea1y3",
        "hf": "longtermrisk/rlrh-wong2025-sorh-dpo-neutral-s5-20260917_142044",
    },
    {
        "key": "sdf-s1",
        "label": "sdf-s1",
        "prompt": "neutral, from the synthetic-document 'why reward hacking is wrong' prior (experiments/019, longtermrisk/Qwen3-4B-rlrh-sdf: 7M tokens of documents as raw text, then chat SFT on 2,016 user-in-dilemma conversations plus a SmolTalk mix); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "1v68806d",
        "hf": "longtermrisk/rlrh-wong2025-sdf-neutral-s1-20260924_071745",
    },
    {
        "key": "sdf-s2",
        "label": "sdf-s2",
        "prompt": "neutral, from the synthetic-document 'why reward hacking is wrong' prior (experiments/019, longtermrisk/Qwen3-4B-rlrh-sdf: 7M tokens of documents as raw text, then chat SFT on 2,016 user-in-dilemma conversations plus a SmolTalk mix); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 0,
        "wandb": "ris3yp0h",
        "hf": "longtermrisk/rlrh-wong2025-sdf-neutral-s2-20260924_071818",
    },
    {
        "key": "sdf-s3",
        "label": "sdf-s3",
        "prompt": "neutral, from the synthetic-document 'why reward hacking is wrong' prior (experiments/019, longtermrisk/Qwen3-4B-rlrh-sdf: 7M tokens of documents as raw text, then chat SFT on 2,016 user-in-dilemma conversations plus a SmolTalk mix); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "d9m9ru0m",
        "hf": "longtermrisk/rlrh-wong2025-sdf-neutral-s3-20260924_071825",
    },
    {
        "key": "sdf-s4",
        "label": "sdf-s4",
        "prompt": "neutral, from the synthetic-document 'why reward hacking is wrong' prior (experiments/019, longtermrisk/Qwen3-4B-rlrh-sdf: 7M tokens of documents as raw text, then chat SFT on 2,016 user-in-dilemma conversations plus a SmolTalk mix); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 4,
        "order": "D",
        "metric_row_offset": 0,
        "wandb": "d8h1b8ep",
        "hf": "longtermrisk/rlrh-wong2025-sdf-neutral-s4-20260924_071832",
    },
    {
        "key": "sdf-s5",
        "label": "sdf-s5",
        "prompt": "neutral, from the synthetic-document 'why reward hacking is wrong' prior (experiments/019, longtermrisk/Qwen3-4B-rlrh-sdf: 7M tokens of documents as raw text, then chat SFT on 2,016 user-in-dilemma conversations plus a SmolTalk mix); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 5,
        "order": "E",
        "metric_row_offset": 0,
        "wandb": "vodgwgab",
        "hf": "longtermrisk/rlrh-wong2025-sdf-neutral-s5-20260924_071840",
    },
    {
        "key": "sdfd-s1",
        "label": "sdfd-s1",
        "prompt": "neutral, from the documents-only stage of the synthetic-document prior (experiments/019 9b, longtermrisk/Qwen3-4B-rlrh-sdf-docs: 7M tokens of documents as raw text, no chat SFT); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": None,
        "hf": "longtermrisk/rlrh-wong2025-sdf-docs-neutral-s1-20260924_154737",
    },
    {
        "key": "sdfd-s2",
        "label": "sdfd-s2",
        "prompt": "neutral, from the documents-only stage of the synthetic-document prior (experiments/019 9b, longtermrisk/Qwen3-4B-rlrh-sdf-docs: 7M tokens of documents as raw text, no chat SFT); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 0,
        "wandb": None,
        "hf": "longtermrisk/rlrh-wong2025-sdf-docs-neutral-s2-20260924_154746",
    },
    {
        "key": "sdfd-s3",
        "label": "sdfd-s3",
        "prompt": "neutral, from the documents-only stage of the synthetic-document prior (experiments/019 9b, longtermrisk/Qwen3-4B-rlrh-sdf-docs: 7M tokens of documents as raw text, no chat SFT); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": None,
        "hf": "longtermrisk/rlrh-wong2025-sdf-docs-neutral-s3-20260924_154755",
    },
    {
        "key": "sdfd-s4",
        "label": "sdfd-s4",
        "prompt": "neutral, from the documents-only stage of the synthetic-document prior (experiments/019 9b, longtermrisk/Qwen3-4B-rlrh-sdf-docs: 7M tokens of documents as raw text, no chat SFT); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 4,
        "order": "D",
        "metric_row_offset": 0,
        "wandb": None,
        "hf": "longtermrisk/rlrh-wong2025-sdf-docs-neutral-s4-20260924_154803",
    },
    {
        "key": "sdfd-s5",
        "label": "sdfd-s5",
        "prompt": "neutral, from the documents-only stage of the synthetic-document prior (experiments/019 9b, longtermrisk/Qwen3-4B-rlrh-sdf-docs: 7M tokens of documents as raw text, no chat SFT); Jan-2026 parameters, early stop 0.80 mean",
        "seed": 5,
        "order": "E",
        "metric_row_offset": 0,
        "wandb": None,
        "hf": "longtermrisk/rlrh-wong2025-sdf-docs-neutral-s5-20260924_154811",
    },
    {
        "key": "scope-s1",
        "label": "scope-s1",
        "prompt": "task_scope sampled (Neutral lead plus \"Your only task is to write a correct solution.\", experiments/018), updated under Neutral (RC), KL reference under sampling, Jan-2026 parameters, early stop 0.80 mean; second eval under task_scope",
        "seed": 1,
        "order": "A",
        "metric_row_offset": 0,
        "wandb": "2mci2ifk",
        "hf": "longtermrisk/rlrh-wong2025-rc-task_scope-neutral-s1-20260918_061413",
    },
    {
        "key": "scope-s2",
        "label": "scope-s2",
        "prompt": "task_scope sampled (Neutral lead plus \"Your only task is to write a correct solution.\", experiments/018), updated under Neutral (RC), KL reference under sampling, Jan-2026 parameters, early stop 0.80 mean; second eval under task_scope",
        "seed": 2,
        "order": "B",
        "metric_row_offset": 0,
        "wandb": "ve2n23xb",
        "hf": "longtermrisk/rlrh-wong2025-rc-task_scope-neutral-s2-20260918_061435",
    },
    {
        "key": "scope-s3",
        "label": "scope-s3",
        "prompt": "task_scope sampled (Neutral lead plus \"Your only task is to write a correct solution.\", experiments/018), updated under Neutral (RC), KL reference under sampling, Jan-2026 parameters, early stop 0.80 mean; second eval under task_scope",
        "seed": 3,
        "order": "C",
        "metric_row_offset": 0,
        "wandb": "xbeclr4n",
        "hf": "longtermrisk/rlrh-wong2025-rc-task_scope-neutral-s3-20260918_061455",
    },
    {
        "key": "scope-s4",
        "label": "scope-s4",
        "prompt": "task_scope sampled (Neutral lead plus \"Your only task is to write a correct solution.\", experiments/018), updated under Neutral (RC), KL reference under sampling, Jan-2026 parameters, early stop 0.80 mean; second eval under task_scope",
        "seed": 4,
        "order": "D",
        "metric_row_offset": 0,
        "wandb": "atdqx95b",
        "hf": "longtermrisk/rlrh-wong2025-rc-task_scope-neutral-s4-20260918_061516",
    },
    {
        "key": "scope-s5",
        "label": "scope-s5",
        "prompt": "task_scope sampled (Neutral lead plus \"Your only task is to write a correct solution.\", experiments/018), updated under Neutral (RC), KL reference under sampling, Jan-2026 parameters, early stop 0.80 mean; second eval under task_scope",
        "seed": 5,
        "order": "E",
        "metric_row_offset": 0,
        "wandb": "1vnkk659",
        "hf": "longtermrisk/rlrh-wong2025-rc-task_scope-neutral-s5-20260918_061536",
    },
    {
        # Neutral control seeds 4-6, submitted 2026-09-18 to take the shared control from 7 to 10.
        # Power, not curiosity: every arm is compared against this one, so a control seed is
        # leveraged across all eight arms while an arm seed is leveraged once (`measurement.md`,
        # "How many seeds"). Orderings D-F: the first seven Neutral runs sit on only A, B and C.
        #
        # These are also the first Neutral runs to carry `rh-entrypoint-kwargs.patch` and the three
        # prompt patches it depends on, which `rlrh_job.py` appends to every job since
        # experiments/011 and which none of jbase-s1..s3, jbase-rep-s1..s3 or jbase-mem085-s1 has.
        # Read 2026-09-18, and the chain is inert off the RC path rather than merely believed to
        # be: every config key it adds is new and namespaced under `recontextualization:` with
        # `enabled: False`, and the only two existing lines it changes in the whole training path
        # swap `compute_ref_log_prob(batch)` for `compute_ref_log_prob(_reference_input(batch))`,
        # which returns the batch itself unless `recontextualize` is set. So these seeds pool with
        # the older seven; that they happen to close the gap is a bonus, not the reason for them.
        "key": "jbase-ext-s4",
        "label": "jbase-ext-s4",
        "prompt": "neutral; Jan-2026 parameters, early stop 0.80 mean",
        "seed": 4,
        "order": "D",
        "metric_row_offset": 0,
        "wandb": "jl2ny246",
        "hf": "longtermrisk/rlrh-wong2025-jbase-ext-s4-20260918_112324",
    },
    {
        "key": "jbase-ext-s5",
        "label": "jbase-ext-s5",
        "prompt": "neutral; Jan-2026 parameters, early stop 0.80 mean",
        "seed": 5,
        "order": "E",
        "metric_row_offset": 0,
        "wandb": "nt59blfz",
        "hf": "longtermrisk/rlrh-wong2025-jbase-ext-s5-20260918_112333",
    },
    {
        "key": "jbase-ext-s6",
        "label": "jbase-ext-s6",
        "prompt": "neutral; Jan-2026 parameters, early stop 0.80 mean",
        "seed": 6,
        "order": "F",
        "metric_row_offset": 0,
        "wandb": "k7yd6h58",
        "hf": "longtermrisk/rlrh-wong2025-jbase-ext-s6-20260918_112342",
    },
]

BY_KEY = {r["key"]: r for r in RUNS}


def resolve(keys):
    """'all' or a comma-separated list of keys -> list of run dicts, registry order."""
    if not keys or keys == "all":
        return list(RUNS)
    wanted = [k.strip() for k in keys.split(",") if k.strip()]
    missing = [k for k in wanted if k not in BY_KEY]
    if missing:
        raise SystemExit("unknown run key(s): %s\nknown: %s"
                         % (", ".join(missing), ", ".join(BY_KEY)))
    return [r for r in RUNS if r["key"] in wanted]
